import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  notes_sidebar: [
    {
      type: "autogenerated",
      dirName: "notes",
    },
  ],
  sugar_ws_sidebar: [
    {
      type: "autogenerated",
      dirName: "sugar-ws",
    },
  ],
  karabiner_json_generator_sidebar: [
    {
      type: "autogenerated",
      dirName: "karabiner-json-generator",
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
